[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "regus_social_media"
version = "0.0.1"

[tool.setuptools]
packages = { find = { where = ["src"] } }
