name: Python Tox Tests

on:
  pull_request:
    branches:
      - main  # Assuming 'main' is your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]  # Adjust based on your needs

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox-conda

    - name: Run Tox
      run: tox
