name: Python CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.11] # Adjust based on your tox envlist

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install tox
      run: python -m pip install --upgrade tox-conda
      
    - name: Run tox
      env:
        META_SANDBOX_API_KEY: ${{ secrets.META_SANDBOX_API_KEY }}
        META_API_KEY: ${{ secrets.META_API_KEY }}
      run: tox
